baseURL = "https://spycat.blog/"
languageCode = "en-us"
title = "Spycat Security"
theme = "terminal"

[pagination]
  pagerSize = 5

[params]
  # "green", "orange", "blue", "red", "pink"
  themeColor = "blue"
  fullWidthTheme = false
  centerTheme = false

  # Social Links
  [params.github]
    username = "spycatt"
  [params.linkedin]
    username = "anas-aljamal"
  [params.email]
    email = "contact@spycat.blog"

  [params.logo]
    logoText = "$ ./spycat.sh"
    logoHomeLink = "/"
    cursor = true

  [params.menu]
    [[params.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
    [[params.menu.main]]
      identifier = "posts"
      name = "Writeups"
      url = "/posts"
