baseURL = "https://spycat.blog/"
languageCode = "en-us"
title = "Spycat Security"
theme = "terminal"

# This forces the date to look like "30-08-2025" (Like hg8.sh)
[params]
  themeColor = "green"
  fullWidthTheme = false
  centerTheme = false
  dateFormat = "02-01-2006"

  [params.logo]
    logoText = "$ ./spycat.sh"
    logoHomeLink = "/"
    cursor = true

  [params.menu]
    [[params.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
    [[params.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/posts"

  # Social links (Optional - allows you to add icons later)
  [params.twitter]
    username = ""
