baseURL = "https://spycat.blog/"
languageCode = "en-us"
title = "Spycat Security"
theme = "terminal"
paginate = 10

[params]
  # 1. Force the Green Color
  themeColor = "green"

  # 2. Force the "List" Layout (Like hg8.sh)
  # This hides the full text and only shows Title + Date
  showFullContent = false
  readingTime = false
  
  # 3. Match the Date Format (dd-mm-yyyy)
  dateFormat = "02-01-2006"

  # 4. Layout Settings
  fullWidthTheme = false
  centerTheme = false

  [params.logo]
    logoText = "$ ./spycat.sh"
    logoHomeLink = "/"
    cursor = true

  [params.menu]
    [[params.menu.main]]
      identifier = "about"
      name = "About"
      url = "/about"
    [[params.menu.main]]
      identifier = "posts"
      name = "Writeups"
      url = "/posts"
